#include "pic.h"
#include "uart.h"

void init_pic() {
	out8(MASTER_PIC_COMMAND, FIRST_WORD);
	out8(MASTER_PIC_DATA, ICW2_MASTER);
	out8(MASTER_PIC_DATA, CONFIG_MASTER);
	out8(MASTER_PIC_DATA, PIC_MODE);

	out8(SLAVE_PIC_COMMAND, FIRST_WORD);
	out8(SLAVE_PIC_DATA, ICW2_SLAVE);
	out8(SLAVE_PIC_DATA, CONFIG_SLAVE);
	out8(SLAVE_PIC_DATA, PIC_MODE);
}